name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        coverage run -m unittest discover
        coverage report
    - name: Upload coverage to Coveralls
      run: |
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=x2late2take_opisanye_proekta
          -Dsonar.organization=x2late2take
          -Dsonar.sources=game
          -Dsonar.tests=tests_snake_game.py
          -Dsonar.python.version=3.8
          -X
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
